mode: live
start_date: 2025-04-01
end_date: 2025-05-01
primary_interval: 1m
initial_cash: 100000
margin_requirement: 0.0
show_reasoning: false
show_agent_graph: true

# Order execution settings
execution:
  enabled: true  # Set to true to enable live trading
  testnet: false   # Use Binance testnet for safety
  max_order_size: 6  # Maximum order size in USD
  min_confidence: 50    # Minimum confidence to execute orders
  execution_interval: "1m"  # Interval for repeated execution (e.g., "1m", "5m", "1h", "1d")

signals:
  intervals: ["1m"]
  tickers: ["1000SATSUSDT", "1MBABYDOGEUSDT", "GALAUSDT", "VETUSDT"]

  strategies: ['MacdStrategy']
# , "RSIStrategy"]
model:
  name: "gpt-4o-mini" # choose your model.
  provider: "openai"  # llm provider.
  base_url: "https://api.openai.com/v1"  # you can change it to your own.

